# Generated by Django 2.1.3 on 2019-01-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memoria', '0002_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tvseries',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
